name: harmony-v1.0-3
channels:
  - r
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - anndata=0.7.6
  - r-base=4.0.2
  - r-argparse=2.0.1
  - r-devtools
  - r-reticulate=1.20
  - r-hdf5r
  - r-harmony
